id: IEA9A9CD5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T17:35:22+00:00'
last_modified: '2022-06-08T05:18:19.252369+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22025
  title: དྲི་མེད་ཀུན་ལྡན་གྱི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4962':
      image_group_id: I1KG21814
      title: ''
      total_pages: 78
      order: 1
      base_file: 4962.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
