id: P005614
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W22025
  title: དྲི་མེད་ཀུན་ལྡན་གྱི་རྣམ་ཐར།
  author: ''
  volumes:
    2404cd58b8eb426da50ef46a569e9e27:
      image_group_id: I1KG21814
      title: ''
      volume_number: 1
      total_pages: 78
      base_file: v001.txt
